### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by samcarter** [luismartingil/cookiecutter-beamer#2]
I have a couple of suggestions about the code created from your template:

- `\usepackage{amsmath,amssymb}` is not necessary, beamer loads these packages automatically. In this case this is not really a problem, but in general I would avoid loading packages again that are already loaded by beamer because users might be tempted to specify additional package options there which will result in option clashes

- Instead of `\usepackage{colortbl}` it is better to load beamer with `\documentclass[xcolor={table}]{beamer}`. This will avoid possible option clashes

-  Instead of `\usepackage{parcolumns}` and `\usepackage{multicol}` I would urge to use beamers own column mechanism. This will provide better support for overlays etc.

- `\usepackage{color}` and `\usepackage{xcolor}` are not necessary. Beamer already loads xcolor

- `\usepackage{url}` is also not really necessary as beamer already loads hyperref

-  `\usepackage{caption}` is normally also not necessary because beamer provides its own mechanism to adjust the appearance of captions

- I would suggest to move `\title` etc. before `\begin{document}` to make sure that it can be used for meaningful pdf meta data. This would also avoid the warning in the log file...

- the `\\` at the end of items are not necessary and might mislead users to use them for linebreaks

**Comment by luismartingil** [comment]
Thanks for your enhancements - will you be willing to create a Pull Request?

**Comment by samcarter** [comment]
@luismartingil  I created a PR. I tested the syntax of the .tex file. I hope that it also works with this cookiecutter thingy...
